# Generated by Django 5.1.4 on 2025-02-25 09:06

import django.db.models.deletion
import tasks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Назва')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Опис')),
                ('due_date', models.DateField(validators=[tasks.models.validate_due_date], verbose_name='Кінцева дата виконання')),
                ('priority', models.CharField(choices=[('Низька', 'Низька'), ('Середня', 'Середня'), ('Висока', 'Висока'), ('Дуже висока', 'Дуже висока')], default='Середня', max_length=12, verbose_name='Важливість')),
                ('status', models.CharField(choices=[('in_progress', 'В процесі'), ('completed', 'Завершене'), ('overdue', 'Прострочене')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата останнього оновлення')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Завдання',
                'verbose_name_plural': 'Завдання',
            },
        ),
        migrations.CreateModel(
            name='OverdueTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overdue_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата пророчення')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overdue_task', to='tasks.task', verbose_name='Завдання')),
            ],
            options={
                'verbose_name': 'Просрочене завдання',
                'verbose_name_plural': 'Просрочені завдання',
            },
        ),
        migrations.CreateModel(
            name='CompletedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата виконання')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completed_task', to='tasks.task', verbose_name='Завдання')),
            ],
            options={
                'verbose_name': 'Виконане завдання',
                'verbose_name_plural': 'Виконані завдання',
            },
        ),
        migrations.CreateModel(
            name='TaskStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tasks', models.PositiveIntegerField(default=0, verbose_name='Всього завдань')),
                ('completed_tasks', models.PositiveIntegerField(default=0, verbose_name='Виконано')),
                ('overdue_tasks', models.PositiveIntegerField(default=0, verbose_name='Просрочено')),
                ('active_tasks', models.PositiveIntegerField(default=0, verbose_name='Активні')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Статистику',
                'verbose_name_plural': 'Статистика',
            },
        ),
    ]
